/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Row from 'components/Row/Row';

const Table1 = styled('div')({
  borderRadius: `24px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const Row1 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row2 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row3 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row4 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row5 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row6 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row7 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row8 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row9 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Row10 = styled(Row)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

function Table(props) {
  return (
    <Table1 className={props.className}>
      <Row1 />
      <Row2 />
      <Row3 />
      <Row4 />
      <Row5 />
      <Row6 />
      <Row7 />
      <Row8 />
      <Row9 />
      <Row10 />
    </Table1>
  );
}

export default Table;
