/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import MenuItem from 'components/MenuItem/MenuItem';

const Menu1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(241, 243, 245, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `1024px`,
  width: '100%',
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
}));

const Frame12 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
});

const Logo = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `32px 0px 0px 40px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const UntitledDesign3Remov = styled('img')({
  height: `40px`,
  width: `134.23px`,
  objectFit: `cover`,
  margin: `0px`,
});

const Frame11 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `48px 0px 0px 0px`,
});

const Menu2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 0px 48px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const MenuItem1 = styled(MenuItem)(({ theme }) => ({
  margin: `0px`,
}));

const MenuItem2 = styled(MenuItem)(({ theme }) => ({
  margin: `24px 0px 0px 0px`,
}));

const MenuItem3 = styled(MenuItem)(({ theme }) => ({
  margin: `24px 0px 0px 0px`,
}));

const MenuItem4 = styled(MenuItem)(({ theme }) => ({
  margin: `24px 0px 0px 0px`,
}));

const MenuItem5 = styled(MenuItem)(({ theme }) => ({
  margin: `24px 0px 0px 0px`,
}));

const MenuItem6 = styled(MenuItem)(({ theme }) => ({
  margin: `24px 0px 0px 0px`,
}));

const MenuItem7 = styled(MenuItem)(({ theme }) => ({
  margin: `24px 0px 0px 0px`,
}));

const UserAccount = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `32px 40px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
});

const Frame9 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Ellipse2 = styled('img')({
  height: `40px`,
  width: `40px`,
  objectFit: `cover`,
  margin: `0px`,
});

const Frame7 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 14px`,
});

const VashonG = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Partner = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(173, 181, 189, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `2px 0px 0px 0px`,
}));

const HeroiconsOutlineElli = styled('img')({
  height: `auto`,
  width: `24px`,
});

function Menu(props) {
  return (
    <Menu1 className={props.className}>
      <Frame12>
        <Logo>
          <UntitledDesign3Remov
            src={`assets/images/Menu_Untitled_design__3__removebg_preview_1.png`}
            loading="lazy"
            alt={'Untitled_design__3_-removebg-preview 1'}
          />
        </Logo>
        <Frame11>
          <Menu2>
            <MenuItem1 />
            <MenuItem2 />
            <MenuItem3 />
            <MenuItem4 />
            <MenuItem5 />
            <MenuItem6 />
            <MenuItem7 />
          </Menu2>
        </Frame11>
      </Frame12>
      <UserAccount>
        <Frame9>
          <Ellipse2
            src={`assets/images/Menu_Ellipse_2.png`}
            loading="lazy"
            alt={'Ellipse 2'}
          />
          <Frame7>
            <VashonG>{`Vashon G.`}</VashonG>
            <Partner>{`Partner`}</Partner>
          </Frame7>
        </Frame9>
        <HeroiconsOutlineElli
          src={`assets/images/Menu_heroicons_outline_ellipsis_horizontal.svg`}
          loading="lazy"
          alt={'heroicons-outline/ellipsis-horizontal'}
        />
      </UserAccount>
    </Menu1>
  );
}

export default Menu;
