/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const Graph1Line1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(241, 243, 245, 1)`,
  borderRadius: `24px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px`,
  boxSizing: `border-box`,
  height: 'auto',
}));

const Frame92 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const AnnualSpend = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `0px`,
}));

const ThisMonth = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(173, 181, 189, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `4px 0px 0px 0px`,
}));

const Group1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `153px`,
  width: `304px`,
  margin: `32px 0px 0px 0px`,
});

const Mar12023 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `14px`,
  textTransform: `none`,
  position: `absolute`,
  left: `44px`,
  top: `139px`,
}));

const Q0 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `14px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `107px`,
}));

const Q5274 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `14px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Mar312023 = styled('div')(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `14px`,
  textTransform: `none`,
  position: `absolute`,
  left: `235px`,
  top: `139px`,
}));

const Line2 = styled('div')({
  border: `0.5px solid rgba(222, 226, 230, 1)`,
  width: `304px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `127px`,
});

const Line5 = styled('div')({
  border: `0.5px solid rgba(222, 226, 230, 1)`,
  width: `304px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `21px`,
});

const Line3 = styled('div')({
  border: `0.5px solid rgba(222, 226, 230, 1)`,
  width: `5px`,
  height: `0px`,
  position: `absolute`,
  left: `47px`,
  top: `131px`,
});

const Line4 = styled('div')({
  border: `0.5px solid rgba(222, 226, 230, 1)`,
  width: `5px`,
  height: `0px`,
  position: `absolute`,
  left: `307px`,
  top: `131px`,
});

const Vector1 = styled('img')({
  height: `106px`,
  width: `259px`,
  position: `absolute`,
  left: `45px`,
  top: `21px`,
});

const Group2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `106px`,
  width: `130px`,
  left: `202px`,
  top: `117px`,
});

const Line6 = styled('div')({
  border: `0.5px solid rgba(134, 142, 150, 1)`,
  width: `106px`,
  height: `0px`,
  position: `absolute`,
  left: `56px`,
  top: `53px`,
});

const Frame110 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.9)`,
  boxShadow: `0px 1px 2px rgba(0, 0, 0, 0.1), 0px 1px 1px rgba(0, 0, 0, 0.06), 0px 0px 1px rgba(0, 0, 0, 0.2)`,
  backdropFilter: `blur(4px)`,
  WebkitBackdropFilter: `blur(4px)`,
  borderRadius: `8px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `6px 8px`,
  boxSizing: `border-box`,
  width: `117px`,
  left: `13px`,
  top: `30px`,
});

const Frame109 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Ellipse3 = styled('img')({
  height: `10px`,
  width: `10px`,
  margin: `0px`,
});

const Mar17 = styled('div')(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(73, 80, 87, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `14px`,
  textTransform: `none`,
  margin: `0px 0px 0px 8px`,
}));

const Q628 = styled('div')(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `14px`,
  textTransform: `none`,
}));

const Group = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `12.76px`,
  height: `15.25px`,
  left: `0px`,
  top: `58px`,
});

const Vector = styled('img')({
  height: `15.25px`,
  width: `12.76px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector2 = styled('img')({
  height: `15.25px`,
  width: `12.76px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector3 = styled('img')({
  height: `3.4px`,
  width: `0px`,
  position: `absolute`,
  left: `10px`,
  top: `9px`,
});

const Vector4 = styled('img')({
  height: `3.4px`,
  width: `0.09px`,
  position: `absolute`,
  left: `8px`,
  top: `9px`,
});

const Vector5 = styled('img')({
  height: `3.4px`,
  width: `0px`,
  position: `absolute`,
  left: `6px`,
  top: `9px`,
});

function Graph1Line(props) {
  return (
    <Graph1Line1 className={props.className}>
      <Frame92>
        <AnnualSpend>{`Annual Spend`}</AnnualSpend>
        <ThisMonth>{`This month`}</ThisMonth>
      </Frame92>
      <Group1>
        <Mar12023>{`Mar 1, 2023`}</Mar12023>
        <Q0>{`$0`}</Q0>
        <Q5274>{`$5,274`}</Q5274>
        <Mar312023>{`Mar 31, 2023`}</Mar312023>
        <Line2></Line2>
        <Line5></Line5>
        <Line3></Line3>
        <Line4></Line4>
        <Vector1
          src={`assets/images/Graph1line_Vector_1.png`}
          loading="lazy"
          alt={'Vector 1'}
        />
      </Group1>
      <Group2>
        <Line6></Line6>
        <Frame110>
          <Frame109>
            <Ellipse3
              src={`assets/images/Graph1line_Ellipse_3.png`}
              loading="lazy"
              alt={'Ellipse 3'}
            />
            <Mar17>{`Mar 17`}</Mar17>
          </Frame109>
          <Q628>{`$628`}</Q628>
        </Frame110>
        <Group>
          <Vector
            src={`assets/images/Graph1line_Vector.png`}
            loading="lazy"
            alt={'Vector'}
          />
          <Vector2
            src={`assets/images/Graph1line_Vector_2.png`}
            loading="lazy"
            alt={'Vector'}
          />
          <Vector3
            src={`assets/images/Graph1line_Vector_3.png`}
            loading="lazy"
            alt={'Vector'}
          />
          <Vector4
            src={`assets/images/Graph1line_Vector_4.png`}
            loading="lazy"
            alt={'Vector'}
          />
          <Vector5
            src={`assets/images/Graph1line_Vector_5.png`}
            loading="lazy"
            alt={'Vector'}
          />
        </Group>
      </Group2>
    </Graph1Line1>
  );
}

export default Graph1Line;
